apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sxn90gjll-nodejs
  janus-idp.io/tekton: sxn90gjll-nodejs
  backstage.io/kubernetes-id: sxn90gjll-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sxn90gjll-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
