apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sxn90gjll-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sxn90gjll-nodejs 
  name: sxn90gjll-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: sxn90gjll-nodejs 
